name:                escape-block-rest
version:             0.1.1.0
github:              "iurii-kyrylenko/escape-block-rest"
license:             BSD3
author:              "Iurii Kyrylenko"
maintainer:          "https://github.com/iurii-kyrylenko"
copyright:           "2020 Iurii Kyrylenko"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/iurii-kyrylenko/escape-block-rest#readme>

dependencies:
- base >= 4.7 && < 5
- scotty
- aeson
- hashmap
- containers
- read-env-var
- wai-cors

library:
  source-dirs: src

executables:
  escape-block-rest-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - escape-block-rest

tests:
  escape-block-rest-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - escape-block-rest
